### ISSUE TITLE
Erreur a la compilation

### ISSUE THREAD

**Issue by djboulette** [HendrikZA/general-playmaker#1]
Bonjour,

Petit probleme a la compilation, une erreur apaprait:
`HutongGames.PlayMaker.ActionCategory' does not contain a definition for `Custom'

Pour corriger le tir il faut rectifier cette ligne:

`[ActionCategory(ActionCategory.Custom)]`

par:

`[ActionCategory("Custom")]`

Note: Custom peut être remplacer par n'importe quelle catégorie existante ou pas.
Si la catégorie n'existe pas elle est automatiquement crée.

Merci encore pour ces fabuleux script ;)

**Comment by HendrikZA** [comment]
Hey there, I've changed the script to use Input category and it will now work :)

Please try again and let me know.

I am working on a much larger OculusGo/GearVR action that does everything all in one. Hope to release it in next few days.
